# Generated by Django 4.0.6 on 2022-08-08 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('reservation', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.reservation')),
                ('room', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.room')),
            ],
        ),
    ]
